// <auto-generated />
namespace Web_test2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SchoolDBConStringv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SchoolDBConStringv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202309070703178_SchoolDBConString-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
